# Launches my memex Tiddlywiki.
# Learn about Vannevar Bush's memex concept: https://en.wikipedia.org/wiki/Memex
alias memex="tiddlywiki ~/Wikis/memex --listen port=8080"
# taskwarrior & timewarrior
alias taw="task"
alias tiw="timew"
alias t="taskwarrior-tui"
# vim
alias v="vim"
# buku
alias b="buku"
# date
alias now="date +'%D %T'"
alias nowd="date +'%D'"
alias nowt="date +'%T'"
# kitty
alias h="kitty --session ~/.dotfiles/dots/startup_sessions/home"
