" vi Compatibility
set nocompatible
" File Types & Syntax
filetype on
filetype plugin on
filetype indent on
syntax on
" Line Numbers
set number
" Horizontal Cursor Line
set cursorline
" Tabs
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
" Backups
set nobackup
" Wrap
set wrap
set linebreak
set textwidth=80
set colorcolumn=80
" Search
set smartcase
set showmatch
set incsearch
set hlsearch
set nohlsearch
" Mode Visibility
set showmode
" History
set history=888
" Auto-Complete
set wildmenu
set wildmode=list:longest,full
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx,*.odt,*.mp4
" Show Commands
set showcmd
" Spellcheck
if version >= 700
  set spl=en spell
  set spell
endif
" Enable Mouse
set mouse=a
set noerrorbells
set hidden
set scrolloff=8

" Plugins ----------------------------------------------------------------------
set nocompatible
filetype plugin on
syntax on
" Install vim-plug:
let data_dir = has('nvim?') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs http://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" Use vim-plug to install plugins:
call plug#begin(has('nvim?') ? stdpath('data') . '/plugged' : '~/.vim/plugged')
Plug 'vimwiki/vimwiki'
call plug#end()
