#!/bin/bash

################################################################################
# links+.sh ####################################################################
################################################################################

LINKS_ATTEMPTED=0;
LINKS_CREATED=0;
LINKS_CORRECT=0;
DIR_DOTS="$HOME/.dotfiles/dots";

# link #####################################################################
# Checks if symbolic links are already made or the related files are missing,
# then creates symbolic links if missing.
# Args:
#   $1 - Path to link's desired destination.
#   $2 - Path to link.
link () {
  LINKS_ATTEMPTED=$((LINKS_ATTEMPTED+1));
  local DESTINATION=$1;
  local LINK=$2;
  printf "🗺️ Checking for $LINK.\n";
  if [ -L $LINK ] ; then
    local EXISTING_DESTINATION=$(readlink "$LINK");
    printf "🔎 Link found: $LINK → $EXISTING_DESTINATION\n";
    if [ -e "$EXISTING_DESTINATION" ] ; then
      if [ "$EXISTING_DESTINATION" == "$DESTINATION" ]; then
        printf "👍 Correct link: $LINK → $EXISTING_DESTINATION\n";
	LINKS_CORRECT=$((LINKS_CORRECT+1));
      else
        printf "👎 Incorrect link: $EXISTING_DESTINATION ≠ $DESTINATION\n";
        delete_file "$LINK" "Incorrect link";
        create_link "$DESTINATION" "$LINK";
      fi
    else
      printf "🪦 Broken link: $LINK\n";
      delete_file "$LINK" "Broken link";
      create_link "$DESTINATION" "$LINK";
    fi
  elif [ -e $LINK ] ; then
    printf "📓 File found: $LINK\n";
    rm $LINK;
    if [ $? == 0 ]; then
      printf "🗑️ File deleted: $LINK\n";
    fi
    create_link "$DESTINATION" "$LINK";
    LINKS_CREATED=$((LINKS_CREATED+1))
  else
    printf "🔎 File not found: $LINK\n"
    create_link "$DESTINATION" "$LINK";
  fi    
  printf "\n";
}

create_link () {
  local DESTINATION=$1;
  local LINK=$2;
  ln -s $DESTINATION $LINK
  if [ $? == 0 ]; then
    printf "🔗 Link created: $LINK → $DESTINATION\n";
    LINKS_CREATED=$((LINKS_CREATED+1))
  fi
}

delete_file () {
  local FILE=$1;
  rm $FILE;
  if [ $? == 0 ]; then 
    if [ -n "$2" ]; then
      local FILE_TYPE=$2;
      printf "🗑️ $FILE_TYPE deleted: $FILE \n";
    else
      printf "🗑️ File deleted: $FILE \n";
    fi
  else
    print_error "$FILE could not be deleted.";
  fi
}

print_error () {
  local MESSAGE=$1;
  printf "❗ Error: $MESSAGE\n";
}

################################################################################

# bash
link "$DIR_DOTS/bash/bashrc" "$HOME/.bashrc";
link "$DIR_DOTS/bash/bash_aliases" "$HOME/.bash_aliases";
# code
link "$DIR_DOTS/code/settings.json" "$HOME/.config/Code/User/settings.json";
# espanso
link "$DIR_DOTS/espanso/base.yml" "$HOME/.config/espanso/match/base.yml";
# git
link "$DIR_DOTS/git/gitconfig" "$HOME/.gitconfig";
# kitty
link "$DIR_DOTS/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf";
# taskwarrior (task)
link "$DIR_DOTS/taskwarrior/taskrc" "$HOME/.taskrc";
# nvim
link "$DIR_DOTS/neovim/init.lua" "$HOME/.config/nvim/init.lua";
# tmux
link "$DIR_DOTS/tmux/tmux.conf" "$HOME/.tmux.conf";
# hyprland
link "$DIR_DOTS/hyprland/hyprland.conf" "$HOME/.config/hypr/hyprland.conf";
# dunst
link "$DIR_DOTS/dunst/dunstrc" "$HOME/.config/dunst/dunstrc";
# waybar
link "$DIR_DOTS/waybar/style.css" "$HOME/.config/waybar/style.css";
link "$DIR_DOTS/waybar/config.jsonc" "$HOME/.config/waybar/config.jsonc";

printf "🔗 $LINKS_CREATED/$LINKS_ATTEMPTED links created.\n"
printf "👍 $LINKS_CORRECT/$LINKS_ATTEMPTED links already correct.\n";
