# taskwarrior & timewarrior
alias t="taskwarrior-tui"
# vim
alias v="nvim"
# buku
alias b="buku"
# date
alias d="date -Iseconds"
# system
alias u="sudo apt update -y; sudo apt upgrade -y; flatpak update"
